### ISSUE TITLE
Empty function ?

### ISSUE THREAD

**Issue by mateimicu** [GabrielDornianu/silly_projects#5]
https://github.com/GabrielDornianu/silly_projects/blob/master/tic_tac_toe/javascript.js#L223
https://github.com/GabrielDornianu/silly_projects/blob/master/tic_tac_toe/javascript.js#L235
https://github.com/GabrielDornianu/silly_projects/blob/master/tic_tac_toe/javascript.js#L239

**Comment by GabrielDornianu** [comment]
Solved
